### ISSUE TITLE
Telegram 采用的是 GPL v2 协议，你无权抽取并将之改为 Apache 2.0 协议

### ISSUE THREAD

**Issue by drakeet** [TangXiaoLv/TelegramGallery#1]
Telegram 开源协议：https://github.com/DrKLO/Telegram/blob/master/LICENSE

**Comment by TangXiaoLv** [comment]
@drakeet 谢谢指正，我以为完全使用Telegram并在此基础上修改才需要遵从一样，由于抽离的是一小部分，并且做了大量修改，是否应该继续保持GPL V2？

**Comment by TangXiaoLv** [comment]
@drakeet 谢谢提醒，调查了下，之前没注意，我会及时改回GPL v2
