### ISSUE TITLE
Duplication of images

### ISSUE THREAD

**Issue by mahirpp** [TangXiaoLv/TelegramGallery#10]
The "GalleryActivity" shows duplicate images for each of the images in the gallery.

**Comment by TangXiaoLv** [comment]
@mahirpp  can you upload the error capture？

**Comment by mahirpp** [comment]
sure!!!

PFA & I believe that there is some kind of issue which causes the
duplication when you try to add multiple images.

Here I am trying to add multiple images with a maximum limit of 3.

Thanks & regards,
Mahir.P.P
