### ISSUE TITLE
Use this library in Fragment

### ISSUE THREAD

**Issue by MansoorJafari** [TangXiaoLv/TelegramGallery#11]
Hi,

How to use this library in fragment.?

thanks.

**Comment by TangXiaoLv** [comment]
@MansoorJafari There is no existing method. You can transplant the source code to your own fragment from `GalleryActivity` , Is basically the same.

**Comment by MansoorJafari** [comment]
Thanks for your answer.
I solve this problem but I have one problem another.

after select video my app crash;

`

 GalleryConfig config = new GalleryConfig.Build()
                            .limitPickPhoto(1)
                            .hintOfPick("only one  video")
                            .filterMimeTypes(new String[]{"video/mp4","video/mov"})
                            .build();

`

**Comment by TangXiaoLv** [comment]
@MansoorJafari can you upload crash log? I can't reproduce the bug

**Comment by MansoorJafari** [comment]
in this library only selected one video
I want get SerializeExtraString and give me an error.

Thanks.

**Comment by moonljt521** [comment]
楼主英语不错~

**Comment by Luhangh** [comment]
点赞

**Comment by Aminul-Haque-Aome** [comment]
onActivityResult() doesn't called when came back from Gallery
