### ISSUE TITLE
use getParcelableExtra instead of getSerializableExtra

### ISSUE THREAD

**Issue by vzizmiyagi** [TangXiaoLv/TelegramGallery#22]
Hello:

Thank you for the library.
I would like to test using getParcelableExtra instead of getSerializable onActivityResult to improve performance. How do I go about setting that up in the library without it crashing?

Thanks!

**Comment by TangXiaoLv** [comment]
@vzizmiyagi ArrayList was implements RandomAccess  which support fast (usually constant time) random access.So pass ArrayList  by getSerializable hava no performance problem.

**Comment by vzizmiyagi** [comment]
Alirght thanks!
