### ISSUE TITLE
video filter 

### ISSUE THREAD

**Issue by yesidlazaro** [TangXiaoLv/TelegramGallery#26]
what is the correct video filter 

`.filterMimeTypes(new String[]{"video/mp4"})`

**Comment by TangXiaoLv** [comment]
@yesidlazaro Above example mean that the "video/mp4"  in the list will be ignored.

**Comment by luongvo** [comment]
@TangXiaoLv The method name in this case maybe too misunderstanding 🤔

**Comment by TangXiaoLv** [comment]
@luongvo Yes, it's true.

**Comment by mishaoshuai** [comment]
would you please tell that how to return a list but not a string when you want to choose multi videos?
