### ISSUE TITLE
photo editor

### ISSUE THREAD

**Issue by peter100u** [TangXiaoLv/TelegramGallery#31]
### 心好累， 作者把相册这块抽取出来， 现在老板却让我把图片编辑(photo editor)那一块抽取出来 ，真心觉得telegram写的真好

**Comment by TangXiaoLv** [comment]
@RelocationTime 性能确实很好，不过代码编排上真的很迷，整个相册组件跟业务是强耦合，抽得挺费劲，图片编辑那块当时我们没那个需求所以就没抽，如果你抽完了欢迎提pr！

**Comment by peter100u** [comment]
#### 我都抽取一个礼拜了，头大了，telegram在整个图片编辑器那块，也是高耦合，强耦合，现在还没有抽取到3/10， 前天把jni so抽取出来了，请问，您在抽取中， 有什么特殊方法和技巧吗，十二分感谢！

**Comment by TangXiaoLv** [comment]
@RelocationTime 没有特别的技巧，断点跟踪下整个相册逻辑，然后就是暴力删业务代码，这样抽取的成功率比较高，我大概抽了3次，加上增加QQ相册的功能花了1周多点

**Comment by peter100u** [comment]
#### 恩恩，我们差不多，但是耗时太久！，不过谢谢您
