### ISSUE TITLE
How can I change strings?

### ISSUE THREAD

**Issue by ismaiI1** [TangXiaoLv/TelegramGallery#33]
How can I replace string for "done","preview","cancel" button texts?

**Comment by TangXiaoLv** [comment]
@invisible66 edit string.xml

**Comment by invisible66** [comment]
@TangXiaoLv "string" or "strings" ? i have "string**s**.xml"

**Comment by ismaiI1** [comment]
@TangXiaoLv I add `<string name="done">Tamam</string>` to my `strings.xml` but "done" button text didn't change.

**Comment by ismaiI1** [comment]
I found. "done" button text was not  "done" :D

`    <string name="Send">Tamam</string>`
`    <string name="Cancel">Vazgeç</string>`
`    <string name="Preview">Önizleme</string>`
