### ISSUE TITLE
How to show images from external memory?

### ISSUE THREAD

**Issue by ismaiI1** [TangXiaoLv/TelegramGallery#34]
Hi, 

I add this library to my app but it's not show images from external memory. it's only show images from `/sdcard/pictures/`. I have a lot pics in `/sdcard/DCIM` and `/external-memory/DCIM`. 
     
I add permissons for external store to AndroidManifest.xml : 
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

Opening Activity :
`                GalleryConfig config = new GalleryConfig.Build()`
`                        .limitPickPhoto(MAX_ATTACHMENT_COUNT)`
`                        .singlePhoto(false)`
`                        .hintOfPick("En fazla " + MAX_ATTACHMENT_COUNT + " resim seçebilirsiniz.")`
`                        .filterMimeTypes(new String[]{"image/jpeg"})`
`                        .build();`
`                GalleryActivity.openActivity(getActivity(), reqCode, config);`

How can I add my images path to this library??

**Comment by TangXiaoLv** [comment]
@invisible66 plz remove filterMimeTypes(new String[]{"image/jpeg"}) and try agian.The mean of 'filterMimeTypes' is that what image type you need igone.

**Comment by ismaiI1** [comment]
@TangXiaoLv. thanks for answer.  I realized and I was writing a comment :)

**Comment by ismaiI1** [comment]
@TangXiaoLv can i hide video? I want to only pick images..

**Comment by TangXiaoLv** [comment]
@invisible66 No public api to use,You can remove pick button in the source.

**Comment by ismaiI1** [comment]
@TangXiaoLv thanks. i think, it can be useful feature

**Comment by TangXiaoLv** [comment]
@invisible66 I will be add this feature in the future.
