### ISSUE TITLE
1.0.4版本 complie 失败。

### ISSUE THREAD

**Issue by xmy1231** [TangXiaoLv/TelegramGallery#36]
Error:Could not find telegramgallery.jar (com.library.tangxiaolv:telegramgallery:1.0.4).
Searched in the following locations:
    https://jcenter.bintray.com/com/library/tangxiaolv/telegramgallery/1.0.4/telegramgallery-1.0.4.jar

**Comment by TangXiaoLv** [comment]
@Jacky-Xu sorry,1.0.4包有点问题，升到1.0.5就好了
