### ISSUE TITLE
图片尺寸最大不超过180的由来

### ISSUE THREAD

**Issue by LinXiaoTao** [TangXiaoLv/TelegramGallery#4]
你好。
在阅读项目的时候，有个地方不是太明白。

```
int size = Math.min(180,
                        Math.min(AndroidUtilities.displaySize.x, AndroidUtilities.displaySize.y)
                                / 4);
```

ImageLoader.java中的第564行，在没有拿到系统缩略图的情况下，根据屏幕分辨率和180中的最小值，去计算图片的缩放比例，这个180是根据什么来得出的。
谢谢

**Comment by TangXiaoLv** [comment]
@LinXiaoTao 180应该是限制取屏幕的宽最大值为720像素，除以4算出来是180，由后面取屏幕宽高较小值/4可以推算出来.

**Comment by LinXiaoTao** [comment]
@TangXiaoLv 不太明白，根据什么得到_180是个理想值_

**Comment by TangXiaoLv** [comment]
@LinXiaoTao 这个参数用来生成图片相册略缩图的最大长和宽，180是适配值，当然150，160都行，经过适配才选择180。并没有特别严谨的推导公式

**Comment by TangXiaoLv** [comment]
@LinXiaoTao 应为宽720px左右的手机市场占有率大，理应有理由选择该参数做最佳适配

**Comment by LinXiaoTao** [comment]
好的，谢谢。
