### ISSUE TITLE
在Fragment中使用的时候，在Fragment的onActivityResult中无反应？

### ISSUE THREAD

**Issue by menghanshi** [TangXiaoLv/TelegramGallery#42]
在Fragment中使用的时候，在Fragment的onActivityResult中无反应，只能在这个Fragment所在的Activity的OnActivityResult中处理么？

**Comment by kwong93** [comment]
I am also having problems getting result back, maybe a function that accepts a fragment instead of activity
```
   public static void openActivity(Fragment fragment, int requestCode, GalleryConfig config) {
        Intent intent = new Intent(activity, GalleryActivity.class);
        intent.putExtra(GALLERY_CONFIG, config);
        fragment.startActivityForResult(intent, requestCode);
    }
```

**Comment by kwong93** [comment]
Just a quick fix I extended GalleryActivity like so, now I am able to get the result within the nested fragment's onActivityResult

```
public class CustomGalleryActivity extends GalleryActivity {
    /**
     * Open gallery with fragment starting the the activity to use onActivityResult
     * in fragment
     */
    public static void openActivity(Fragment fragment, int requestCode, GalleryConfig config) {
        Intent intent = new Intent(fragment.getContext(), GalleryActivity.class);
        intent.putExtra("GALLERY_CONFIG", config);
        fragment.startActivityForResult(intent, requestCode);
    }
}

```

**Comment by manyunyu7** [comment]
> Just a quick fix I extended GalleryActivity like so, now I am able to get the result within the nested fragment's onActivityResult
> 
> ```
> public class CustomGalleryActivity extends GalleryActivity {
>     /**
>      * Open gallery with fragment starting the the activity to use onActivityResult
>      * in fragment
>      */
>     public static void openActivity(Fragment fragment, int requestCode, GalleryConfig config) {
>         Intent intent = new Intent(fragment.getContext(), GalleryActivity.class);
>         intent.putExtra("GALLERY_CONFIG", config);
>         fragment.startActivityForResult(intent, requestCode);
>     }
> }
> ```

Thanks, works well on me.
