### ISSUE TITLE
为什么取消选中图片，数字不会刷新...

### ISSUE THREAD

**Issue by zaaach** [TangXiaoLv/TelegramGallery#5]

**Comment by TangXiaoLv** [comment]
@zaaach 能描述下具体复现步骤，以及机型么？

**Comment by zaaach** [comment]
比如我选择了3张图片，界面上数字是1,2,3，我取消数字2，界面上的数字应该刷新成1,2的，但是没有刷新

**Comment by zaaach** [comment]
把hasCamera改为true也没见到在哪可以拍照。。手机华为荣耀3C

**Comment by TangXiaoLv** [comment]
@zaaach 数字不刷新就是这个机制，这个可以做到比较灵活的排序问题，比如1，2，3，取消2，这时预览，你会发现预览顺序就是1，2(就是选中的3)，点击完成就按序号从低到高顺序排序发送。如果此时界面只有1，3，你选择其他照片，这张被选中照片序号就是为2，再次选择的照片就从4开始。这么设计可以做到非常灵活的选择照片排序问题

**Comment by TangXiaoLv** [comment]
@zaaach hasCamera目前只留了接口，未实现！

**Comment by zaaach** [comment]
界面上最大的数字可能会和右下角选择的总数不一致，总感觉有些别扭，强迫症。。。
