### ISSUE TITLE
Incomplete string resource file

### ISSUE THREAD

**Issue by mahirpp** [TangXiaoLv/TelegramGallery#6]
one particular resource item is missing in string.xml file under values-en that is available in the other language.
"MostSelect", which is the message showing when there more selection of images than permitted limit.
Currently  this message is showing in a different language and not in English.

**Comment by TangXiaoLv** [comment]
@mahirpp im forget test all case，thx for reminding

**Comment by bradmartin** [comment]
Would be nice to have a public method to set this string value also before opening the Activity. 👍

**Comment by rahmatrasyidi** [comment]
@TangXiaoLv message for most selection images still showing in different language

**Comment by mahirpp** [comment]
@TangXiaoLv  can you please fix up this issue asap or kindly provide me with a solution.?

**Comment by TangXiaoLv** [comment]
sorry everybody ，recently too busy！
@mahirpp pls use compile 'com.library.tangxiaolv:telegramgallery:1.0.2'
@bradmartin 1.0.2 has supported

**Comment by TangXiaoLv** [comment]
@rahmatrasyidi try 1.0.2
