### ISSUE TITLE
Error:No service of type Factory Occurred

### ISSUE THREAD

**Issue by mohanrajtrade** [TangXiaoLv/TelegramGallery#7]
Gradle 'TelegramGallery-master' project refresh failed
Error:No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.

**Comment by TangXiaoLv** [comment]
@mohanrajtrade Can you show me the detailed error log

**Comment by chengzichen** [comment]
@mohanrajtrade 

if you use Android Studio 2.2  change      maven-gradle-plugin:1.5

in build.gradle   :

 dependencies {
   ......
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
  ......
    }

**Comment by gejiaheng** [comment]
@chengzichen Thanks, it works.
