### ISSUE TITLE
你写的很好,一直关注,怎么修改主题颜色值,和一些简单的布局,还有可以不可以先跳转到选择哪个相册那个页面

### ISSUE THREAD

**Issue by chengzichen** [TangXiaoLv/TelegramGallery#8]

**Comment by TangXiaoLv** [comment]
@chengzichen 目前暂未支持这些扩展，由于最近比较忙，会暂缓一段时间，你可以自己尝试着自己扩展，更改主题颜色建议不错

**Comment by chengzichen** [comment]
@TangXiaoLv 可以可以,是不是在Theme里面修改?

**Comment by TangXiaoLv** [comment]
@chengzichen 不是，代码改，可以抽出个Theme接口

**Comment by chengzichen** [comment]
我项目中现在想用 @TangXiaoLv ,还有个情况你查找到的图片有些是空的,显示不出来

**Comment by TangXiaoLv** [comment]
@chengzichen 方便截图看看么

**Comment by chengzichen** [comment]
![image](https://cloud.githubusercontent.com/assets/19171614/19372309/47941444-91ed-11e6-8390-2c8a2faf2022.png)

**Comment by chengzichen** [comment]
@TangXiaoLv 小米2s老手机测试

**Comment by chengzichen** [comment]
如果我要修改布局主题颜色是在你源码的Theme类里面颜色值可以吗?

**Comment by TangXiaoLv** [comment]
@chengzichen 你本地怎么修改都可以

**Comment by TangXiaoLv** [comment]
@chengzichen 这是什么样的特殊图片 ，我这边模拟不出来

**Comment by chengzichen** [comment]
那个图片是截图，过段时间有没有了,可能是没刷新或者系统问题吧,个人认为,选择照片应该是选择相册，再选择图片，3q a nice day @TangXiaoLv
